export const  ADD_CHRONO = 'ADD_CHRONO';
export const  REMOVE_CHRONO = 'REMOVE_CHRONO';
export const  ADD_TIMEOUT = 'ADD_TIMEOUT';
export const  REMOVE_TIMEOUT = 'REMOVE_TIMEOUT';
export const SET_BLUR_TIMESTAMP = 'SET_BLUR_TIMESTAMP';
export const SET_IS_RUNNING = 'SET_IS_RUNNING';
